server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    password: ohgiraffers
    username: ohgiraffers
    url: jdbc:mysql://localhost:3306/ohgiraffers
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key: sdfadsfsdfadsfasdfasdfasdfsdfnw4tn23n4on1k5n1k2n14369hn
  time: 86400000